config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ai_chats, only: [ :create ] do
    resources :ai_chat_messages, only: [ :index, :create ]
  end
  # get 'users/profile', to: 'users#profile'
  # patch 'users/profile', to: 'users#update_profile', as: 'user_update_profile'


  get '/requests', to: 'therapy_requests#requests'
  get "/messages(/:appointment_id)", to: "psychologist_messages#index", as: :messages

  resources :psychologists, only: [ :index, :show ], controller: "users" do
    resources :appointments, only: [ :new, :create ]
  end
  resources :appointments, except: [:new, :create] do
  delete :destroy_conversation, on: :member
  delete :destroy_appointment, on: :member
  resources :psychologist_messages, only: [:index, :create] do
    delete :destroy_chat, on: :collection
  end
  resource :review, only: [:new, :create]
end
  resources :schedules
  resources :therapy_requests, only: [ :create, :update, :destroy ]
  resources :questions, only: [:create] do
    collection do
      delete :destroy_all
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
  get "/dashboard", to: "users#dashboard"
end

app/views/shared/_flashes.html.erb
<% if notice && !["Signed out successfully.", "Signed in successfully."].include?(notice) %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid <%= 'justify-content-end' if minimal %>">
    <% unless minimal %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logomindme.jpg" %>
      <% end %>

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", "#", class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="">
            <%= link_to "Hola, #{current_user.first_name}", "#", class: "nav-link" %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "rounded-circle", style: "object-fit: cover; width: 40px; height: 40px;" %>
            <% else %>
              <%= image_tag "default-avatar.png", class: "rounded-circle", style: "width: 40px; height: 40px;" %>
            <% end %>

          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>